### ISSUE TITLE
Append relative path when using local tag

### ISSUE THREAD

**Issue by abdonrd** [foray1010/ignore-sync#299]
I want to use this package in a mono-repo, but I have run into a problem: when using the `[local]` tag, the output code does not have the relative path appended. Example:

Input `.prettierignore-sync`:
```
[local]
.gitignore
packages/benchmarks/.gitignore
```

Output `.prettierignore`:

```
############################################
# GENERATED BY IGNORE-SYNC, DO NOT EDIT!!! #
# https://github.com/foray1010/ignore-sync #
############################################

node_modules/
lerna-debug.log

generated/
generator/build/
generator/generated/
```

But I expect this output:

```
############################################
# GENERATED BY IGNORE-SYNC, DO NOT EDIT!!! #
# https://github.com/foray1010/ignore-sync #
############################################

node_modules/
lerna-debug.log

packages/benchmarks/generated/
packages/benchmarks/generator/build/
packages/benchmarks/generator/generated/
```

Otherwise it gives me conflicts with other packages that I don't want to ignore.

**Comment by foray1010** [comment]
Why you need to copy the package's .gitignore to the root .gitignore? Both your /.gitignore and /packages/*/.gitignore will be resolved by git

**Comment by abdonrd** [comment]
It's for Prettier & ESLint, not for git.

**Comment by foray1010** [comment]
The reason of this behavior is because `ignore-sync` treat those dependencies as template that are for copy and paste, so the path inside is not relative to the destination file

For example, `/packages/a/.npmignore` can copy the `/.gitignore` directly, without messing up the files with prefix `../../`.

And user can define file structure like the following code, so that the ignore files can be stored in different directory

```ini
[local]
.config/commonignore
```

It works the same for remote config
```ini
[github/gitignore]
Node.gitignore
Global/macOS.gitignore
```

Therefore, it does not work the way that solve your problem.

With that being said, we can introduce a new tag like `[relative]` for this different behavior, if you wanna help coding it.

**Comment by abdonrd** [comment]
Without having read your comment yet, I was just submitting this proposal: #301

**Comment by abdonrd** [comment]
@foray1010 PR updated with your comments!

**Comment by foray1010** [comment]
`3.0.0` released🎉
